### ISSUE TITLE
Create Cloud Foundry and Invite Team Member

### ISSUE THREAD

**Issue by abdulrahimq** [nyu-devops-2021-summer-promotions/promotions#52]
**As a** developer
**I need** to be able to invite team members to the cloud
**So that** able to upload code to the cloud

**Assumptions:** 
* FYI: 00-Invite-to-IBMCloud.pdf

**Acceptance Criteria:**
```
Given IBM Cloud
Then the status of all members changed to ACTIVE

Given that team member was invited 
Then they are able to upload service to the could without errors.
```

**Comment by jtsen** [comment]
Hey, I could see that all of the groupmates being assigned to the dev-ops group. However, I can't seem to find an organization? I'm referring to the image below:


![image](https://user-images.githubusercontent.com/47133306/126213301-8ad56575-6467-483e-9c06-2aabe9002c56.png)

It seems like, in the professor's slides, that we would have to create an organization with manager/developer settings? Let me know if this makes sense and if I'm missing something.

**Comment by shihokuni** [comment]
@jtsen  thank you for checking!

![スクリーンショット 2021-07-19 19 46 38](https://user-images.githubusercontent.com/44769660/126241451-5577d5c5-b3b0-4f7f-9a06-cfebe02334b4.png)

I think we can't add organization when we use this free account. So that, I thought all of us use my account (org is sk8536@nyu.edu) we can change the name. but I think the name of the organization is anything ok. I'm not sure about my idea though...
